name: Validate csv data

on:
  push:
    paths:
    - '*.csv'

jobs: 
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: validate
      run: | 
        sudo npm install -g csval
        ./validate_csv.sh
